version: '3'

services:
  php82:
    image: kooldev/php:8.2
    ports:
      - "9082:9000"
    volumes:
      - ./www/site-01:/var/www/html

  php81:
    image: kooldev/php:8.1
    ports:
      - "9081:9000"
    volumes:
      - ./www/site-02:/var/www/html


  php74:
    image: kooldev/php:7.4
    ports:
      - "9074:9000"
    volumes:
      - ./www/site-03:/var/www/html
