version: '3'

services:
  php82:
    container_name: php82
    image: kooldev/php:8.2-nginx
    ports:
      - "9082:80"
    volumes:
      - ./www/site-01:/app/public

  php81:
    container_name: php81-nginx
    image: kooldev/php:8.1-nginxgit 
    ports:
      - "9081:80"
    volumes:
      - ./www/site-02:/app/public


  php74:
    container_name: php74
    image: kooldev/php:7.4-nginx
    ports:
      - "9074:80"
    volumes:
      - ./www/site-03:/app/public

